service: bus-api

frameworkVersion: '2'
useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: local
  region: eu-central-1
  apiGateway:
    shouldStartNameWithService: true

plugins:
  - serverless-offline
  - serverless-webpack

custom: ${file(./src/serverless/custom.yml):${self:provider.stage}}

functions:
  - ${file(./src/handlers/system/functions.yml)}
  - ${file(./src/handlers/bus-stops/functions.yml)}
